# Generated by Django 4.2.4 on 2023-09-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCompleto', models.CharField(max_length=50)),
                ('emp_code', models.CharField(max_length=3)),
                ('telefone', models.CharField(max_length=25)),
            ],
        ),
    ]
